# Generated by Django 4.0.6 on 2022-08-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
